spring:
  datasource:
    url: jdbc:mysql://sql.servidor.homologacao:3306/dbspotmusic?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: imap.2019
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: update
    database: mysql