spring:
  datasource:
    url: jdbc:mysql://10.10.10.6:3306/dbspotmusic?useSSL=false&createDatabaseIfNotExist=true
    username: id4ni10
    password: k4d1l4k!
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: update
    database: mysql